# Generated by Django 3.1.5 on 2022-05-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20190310_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='aloqa',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
