# Generated by Django 4.2.2 on 2023-07-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_comment_id_alter_restaurant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='persons',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='price',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='taste',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='vat',
        ),
    ]
