# Generated by Django 4.2.2 on 2023-09-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_remove_restaurant_persons_remove_restaurant_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='aloqa',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='location',
        ),
    ]
